# Generated by Django 4.2 on 2023-05-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
