# Generated by Django 4.2 on 2023-05-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
