# Generated by Django 4.2 on 2023-05-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mercado_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remainder_sended',
            field=models.BooleanField(default=False),
        ),
    ]
