# Generated by Django 4.2.1 on 2023-05-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_mercado_link_order_remainder_sended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remainder_sended',
            new_name='reminder_sended',
        ),
    ]
