# Generated by Django 4.2 on 2023-04-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdocumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentation',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('passport', 'passport'), ('drivers_license', 'drivers_license')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdocumentation',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
