# Generated by Django 4.2 on 2023-05-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentation',
            name='is_distinguished',
            field=models.BooleanField(default=False),
        ),
    ]
