# Generated by Django 4.2 on 2023-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userdocumentation_is_distinguished'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_distinguished',
            field=models.BooleanField(default=False),
        ),
    ]
